version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting an AWS account creation action"

  build:
    commands:
      - echo "Processing request..."
      - ./create_aws_account_using_cli.sh 
      - echo "AWS account creation is completed successfully"

  post_build:
    commands:
      - |
        # Send completion notification
        aws lambda invoke \
          --function-name ${NOTIFIER_FUNCTION_NAME} \
          --payload "{\"notification_type\":\"direct-message\",\"user_id\":\"${USER_ID}\",\"message\":\"✅ AWS account creation is completed successfully!\"}" \
          response.json
      - cat response.json
